# Generated by Django 4.2.16 on 2024-11-11 18:52

import django.core.serializers.json
from django.db import migrations, models
import django.db.models.deletion
import nautobot.core.models.fields
import nautobot.extras.models.mixins
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('extras', '0116_fix_dynamic_group_group_type_data_migration'),
        ('dcim', '0062_module_data_migration'),
    ]

    operations = [
        migrations.CreateModel(
            name='Weather',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('last_updated', models.DateTimeField(auto_now=True, null=True)),
                ('_custom_field_data', models.JSONField(blank=True, default=dict, encoder=django.core.serializers.json.DjangoJSONEncoder)),
                ('short_forecast', models.CharField(max_length=255)),
                ('temperature', models.IntegerField()),
                ('probability_of_precipitation', models.IntegerField()),
                ('relative_humidity', models.IntegerField()),
                ('wind_speed', models.CharField(max_length=255)),
                ('wind_direction', models.CharField(max_length=255)),
                ('location', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='dcim.location')),
                ('tags', nautobot.core.models.fields.TagsField(through='extras.TaggedItem', to='extras.Tag')),
            ],
            options={
                'ordering': ['location'],
            },
            bases=(nautobot.extras.models.mixins.DynamicGroupMixin, nautobot.extras.models.mixins.NotesMixin, models.Model),
        ),
    ]
