# Generated by Django 4.2.16 on 2024-11-15 15:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dcim', '0062_module_data_migration'),
        ('weather_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='weather',
            options={'ordering': ['location', 'short_forecast', 'temperature', 'probability_of_precipitation', 'relative_humidity', 'wind_speed', 'wind_direction']},
        ),
        migrations.AlterField(
            model_name='weather',
            name='location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='weather', to='dcim.location'),
        ),
    ]
