# Generated by Django 4.2.16 on 2024-11-15 15:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dcim', '0062_module_data_migration'),
        ('weather_app', '0002_alter_weather_options_alter_weather_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='weather',
            name='location',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='dcim.location'),
        ),
    ]
