# Generated by Django 3.2.24 on 2024-03-14 18:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('weather', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='weather',
            old_name='wind_direction',
            new_name='wind',
        ),
        migrations.RemoveField(
            model_name='weather',
            name='wind_speed',
        ),
    ]
